file1=open("sample.txt","r")
if file1.mode == 'r':
	file_contents = file1.read()
print (file_contents)
file1.close()
str1 = raw_input("Enter the first string:")
str2 = raw_input("Enter the first string:")
print("string1:",str1)
print("string2:",str2)
file1=open("sample.txt","r")
file_contents = file1.read()
newdata = file_contents.replace(str1,str2)
file1=open("sample.txt","w+")
file1.write(newdata)
file1.close()
